---
title: "KSPZV1 In vitro sporozoite pre-exposure on primary monocytes"
author: "Tuan M. Tran"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Objective

Analyze and plot data from in vitro PfSPZ pre-exposure experiments on primary monocytes

```{r load packages}
library(readxl)
library(writexl)
library(ggplot2)
library(ggpubr)
library(tidyverse)
```

## Read in data

```{r readin data, echo=FALSE}
pheno_exp1 <- read_excel("/Users/tuantran/Library/CloudStorage/OneDrive-IndianaUniversity/Manuscripts/KSPZV1 Manuscript/JCI Resubmission April 2023/KSPZV1_JCI revision_JB/Final data from all Mono and Pfspz experiments/Final figures for KSPZV1-JCI manuscript/Additional data for Tuan/Exp1_Pheno data_All markers_All cell subsets_JB_11282023.xlsx", sheet = 1) %>%
  mutate(experiment = 1)

pheno_exp2 <- read_excel("/Users/tuantran/Library/CloudStorage/OneDrive-IndianaUniversity/Manuscripts/KSPZV1 Manuscript/JCI Resubmission April 2023/KSPZV1_JCI revision_JB/Final data from all Mono and Pfspz experiments/Final figures for KSPZV1-JCI manuscript/Additional data for Tuan/Exp2_Pheno data_All markers_All cell subsets_JB_11282023.xlsx", sheet = 1) %>%
  mutate(experiment = 2)

all_dat <- bind_rows(pheno_exp1,
                     pheno_exp2)
```

## Plot data

```{r arrange plot data, fig.align='center', fig.width=16, fig.height=12}
all_dat2 <- all_dat %>%
  mutate(Treatment = factor(Treatment, levels = c("media only", "1° Pfspz, no 2°Pfspz","mock 1°, 2°Pfspz", "1° and 2°Pfspz"))) 
  

all_dat2_MFI_max <- all_dat2 %>%
  group_by(experiment, Markers, Celltype) %>%
  summarize(y_max = max(MFI)) %>%
  mutate(y_max_new_limit = y_max*1.1) %>%
  ungroup()
  
all_dat2 <- all_dat2 %>%
  left_join(., all_dat2_MFI_max,
             by = c("experiment", "Markers", "Celltype"))

my_comparisons <- list(c("media only", "1° and 2°Pfspz"),
                     c("1° Pfspz, no 2°Pfspz", "1° and 2°Pfspz"),
                     c("mock 1°, 2°Pfspz", "1° and 2°Pfspz"))
                     
pheno_plot_exp1 <- all_dat2 %>%
  filter(experiment==1) %>%
  ggplot(., aes(x = Treatment, y = MFI, color = Treatment)) +
  geom_point() +
  stat_summary(fun = "mean", fun.min = "mean", fun.max= "mean", size= 0.2, geom = "crossbar", color = "black") +
  stat_compare_means(comparisons = my_comparisons,
                     label = "p.signif",                     
                     method = "t.test",
                     paired=FALSE,
                     tip.length=0,
                     step.increase = 0.1)  +
  scale_y_continuous(expand = expansion(mult = c(0, 0.15))) +
  ggh4x::facet_grid2(Celltype~Markers, scales = "free_y", independent = "y") +
  theme_bw() +
  theme(legend.position = "top") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

pheno_plot_exp2 <- all_dat2 %>%
  filter(experiment==2) %>%
  ggplot(., aes(x = Treatment, y = MFI, color = Treatment)) +
  geom_point() +
  stat_summary(fun = "mean", fun.min = "mean", fun.max= "mean", size= 0.2, geom = "crossbar", color = "black") +
  stat_compare_means(comparisons = my_comparisons,
                     label = "p.signif",
                     method = "t.test  ",
                     paired=FALSE,
                     tip.length=0,
                     step.increase = 0.1)  +
  scale_y_continuous(expand = expansion(mult = c(0, 0.15))) +  
  ggh4x::facet_grid2(Celltype~Markers, scales = "free_y", independent = "y") +
  theme_bw() +
  theme(legend.position = "top") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
```

```{r plot data, fig.align='center', fig.width=16, fig.height=12}
ggarrange(pheno_plot_exp1, pheno_plot_exp2, labels = c("Expt 1", "Expt 2") ,nrow = 2)
```

### Normalize values

```{r normalize}
all_dat2 <- all_dat %>%
  mutate(Treatment = factor(Treatment, levels = c("media only", "1° Pfspz, no 2°Pfspz","mock 1°, 2°Pfspz", "1° and 2°Pfspz"))) 

all_dat_all_median <- all_dat2 %>%
  group_by(Celltype, Markers) %>%
  summarize(all_median = median(MFI)) %>%
  ungroup()

all_dat_exp1_median <- all_dat2 %>%
  filter(experiment == 1) %>%
  group_by(Celltype, Markers) %>%
  summarize(exp1_median = median(MFI)) %>%
  ungroup()

all_dat_exp2_median <- all_dat2 %>%
  filter(experiment == 2) %>%
  group_by(Celltype, Markers) %>%
  summarize(exp2_median = median(MFI)) %>%
  ungroup()

median_norm_factors <- all_dat_exp1_median %>%
  left_join(., all_dat_exp2_median,
            by = c("Celltype", "Markers")) %>%
  left_join(., all_dat_all_median,
            by = c("Celltype", "Markers")) %>%
  mutate(exp1_norm_factor = all_median/exp1_median) %>%
  mutate(exp2_norm_factor = all_median/exp2_median) %>%
  pivot_longer(., cols = c(exp1_norm_factor, exp2_norm_factor),
               names_to = "experiment_dummy", values_to = "norm_factor") %>%
  mutate(experiment = ifelse(experiment_dummy == "exp1_norm_factor", 1, 2))

all_dat3 <- all_dat2 %>%
  left_join(., median_norm_factors  %>%
              dplyr::select(-c(exp1_median:experiment_dummy)),
            by = c("Celltype", "Markers", "experiment")) %>%
  mutate(normalized_MFI = MFI*norm_factor) %>%
  mutate(experiment = factor(experiment, labels = c("Expt 1", "Expt 2")))
```

### Plot normalized data

```{r arrange plot normalized data, fig.align='center', fig.width=12, fig.height=6}
my_comparisons <- list(c("media only", "1° and 2°Pfspz"),
                     c("1° Pfspz, no 2°Pfspz", "1° and 2°Pfspz"),
                     c("mock 1°, 2°Pfspz", "1° and 2°Pfspz"))

my_comparisons <- list(c("media only", "1° Pfspz, no 2°Pfspz"),
                       c("media only", "mock 1°, 2°Pfspz"),
                       c("media only", "1° and 2°Pfspz"),
                       c("1° Pfspz, no 2°Pfspz", "1° and 2°Pfspz"),
                       c("mock 1°, 2°Pfspz", "1° and 2°Pfspz"))

pheno_plot_normalized_MFI <- all_dat3 %>%
  ggplot(., aes(x = Treatment, y = normalized_MFI, color = experiment)) +
  geom_point() +
  stat_summary(fun = "mean", fun.min = "mean", fun.max= "mean", size= 0.2, geom = "crossbar", color = "black") +
  stat_compare_means(comparisons = my_comparisons,
                     label = "p.signif",
                     method = "wilcox.test",
                     paired=FALSE,
                     tip.length=0,
                     step.increase = 0.15)  +
  scale_y_continuous(expand = expansion(mult = c(0, 0.15))) + 
  scale_colour_viridis_d() +
  ggh4x::facet_grid2(Celltype~Markers, scales = "free_y", independent = "y") +
  theme_bw() +
  theme(legend.position = "top") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

pheno_plot_normalized_MFI
```



```{r arrange plot normalized data CD14 subsets, fig.align='center', fig.width=9, fig.height=8.25}
my_comparisons <- list(c("media only", "1° and 2°Pfspz"),
                     c("1° Pfspz, no 2°Pfspz", "1° and 2°Pfspz"),
                     c("mock 1°, 2°Pfspz", "1° and 2°Pfspz"))

my_comparisons <- list(c("media only", "1° Pfspz, no 2°Pfspz"),
                       c("media only", "mock 1°, 2°Pfspz"),
                       c("media only", "1° and 2°Pfspz"),
                       c("1° Pfspz, no 2°Pfspz", "1° and 2°Pfspz"),
                       c("mock 1°, 2°Pfspz", "1° and 2°Pfspz"))

all_dat_CD14 <- all_dat3 %>%
  filter(Markers %in% c("CD25","CD80", "CD86", "HLADR")) 

pheno_plot_normalized_MFI <- all_dat_CD14 %>%
  ggplot(., aes(x = Treatment, y = normalized_MFI, color = experiment)) +
  ggbeeswarm::geom_quasirandom() +
  stat_summary(fun = "median", fun.min = "median", fun.max= "median", size= 0.2, geom = "crossbar", color = "black") +
  stat_compare_means(comparisons = my_comparisons,
                     label = "p.signif",
                     method = "wilcox.test",
                     paired=FALSE,
                     tip.length=0,
                     step.increase = 0.125)  +
  scale_y_continuous(expand = expansion(mult = c(0.1, 0.1))) + 
  scale_color_brewer(palette = "Set1") +
  ylab("normalized MFI") +
  ggh4x::facet_grid2(Celltype~Markers, scales = "free_y", independent = "y") +
  theme_bw() +
  theme(legend.position = "top") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

pheno_plot_normalized_MFI
```


```{r save plots CD14 subsets}
figdir <- "/Users/tuantran/Library/CloudStorage/OneDrive-IndianaUniversity/Manuscripts/KSPZV1 Manuscript/JCI Resubmission April 2023/Figures JCI resubmission/"
cairo_pdf(filename = paste0(figdir, "Figure SX Monocyte all subsets PfSPZ preexposure.pdf"), width = 9, height = 8)
pheno_plot_normalized_MFI
dev.off()
```


```{r arrange plot normalized data CD14 total, fig.align='center', fig.width=9, fig.height=4}
my_comparisons <- list(c("media only", "1° and 2°Pfspz"),
                     c("1° Pfspz, no 2°Pfspz", "1° and 2°Pfspz"),
                     c("mock 1°, 2°Pfspz", "1° and 2°Pfspz"))

my_comparisons <- list(c("media only", "1° Pfspz, no 2°Pfspz"),
                       c("media only", "mock 1°, 2°Pfspz"),
                       c("media only", "1° and 2°Pfspz"),
                       c("1° Pfspz, no 2°Pfspz", "1° and 2°Pfspz"),
                       c("mock 1°, 2°Pfspz", "1° and 2°Pfspz"))

all_dat_CD14 <- all_dat3 %>%
  filter(Celltype == "Total CD14+ cells") %>%
  filter(Markers %in% c("CD25","CD80", "CD86", "HLADR")) 

pheno_plot_normalized_MFI <- all_dat_CD14 %>%
  ggplot(., aes(x = Treatment, y = normalized_MFI, color = experiment)) +
  ggbeeswarm::geom_quasirandom() +
  stat_summary(fun = "median", fun.min = "median", fun.max= "median", size= 0.2, geom = "crossbar", color = "black") +
  stat_compare_means(comparisons = my_comparisons,
                     label = "p.signif",
                     method = "wilcox.test",
                     paired=FALSE,
                     tip.length=0,
                     step.increase = 0.125)  +
  scale_y_continuous(expand = expansion(mult = c(0.1, 0.1))) + 
  scale_color_brewer(palette = "Set1") +
  ylab("normalized MFI") +
  ggh4x::facet_grid2(~Markers, scales = "free_y", independent = "y") +
  theme_bw() +
  theme(legend.position = "top") +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))

pheno_plot_normalized_MFI
```


```{r save plots CD14 tota}
figdir <- "/Users/tuantran/Library/CloudStorage/OneDrive-IndianaUniversity/Manuscripts/KSPZV1 Manuscript/JCI Resubmission April 2023/Figures JCI resubmission/"
cairo_pdf(filename = paste0(figdir, "Figure S10B Monocyte PfSPZ preexposure.pdf"), width = 9, height = 3.75)
pheno_plot_normalized_MFI
dev.off()
```